/*
 * Automatically generated by jrpcgen 1.0.7 on 16/1/15 8:19 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.io.OutputStreamWriter;
import java.io.FileWriter;

import java.net.InetAddress;

/**
 * The class <code>getAccTypeClient</code> implements the client stub proxy
 * for the BANK_ACCOUNT_PROG remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class getAccTypeClient extends OncRpcClientStub {

    /**
     * Constructs a <code>getAccTypeClient</code> client stub proxy object
     * from which the BANK_ACCOUNT_PROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public getAccTypeClient(InetAddress host, int protocol)
           throws OncRpcException, IOException {
        super(host, getAccType.BANK_ACCOUNT_PROG, 1, 0, protocol);
    }

    /**
     * Constructs a <code>getAccTypeClient</code> client stub proxy object
     * from which the BANK_ACCOUNT_PROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public getAccTypeClient(InetAddress host, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, getAccType.BANK_ACCOUNT_PROG, 1, port, protocol);
    }

    /**
     * Constructs a <code>getAccTypeClient</code> client stub proxy object
     * from which the BANK_ACCOUNT_PROG remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public getAccTypeClient(OncRpcClient client)
           throws OncRpcException, IOException {
        super(client);
    }

    /**
     * Constructs a <code>getAccTypeClient</code> client stub proxy object
     * from which the BANK_ACCOUNT_PROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public getAccTypeClient(InetAddress host, int program, int version, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, 0, protocol);
    }

    /**
     * Constructs a <code>getAccTypeClient</code> client stub proxy object
     * from which the BANK_ACCOUNT_PROG remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public getAccTypeClient(InetAddress host, int program, int version, int port, int protocol)
           throws OncRpcException, IOException {
        super(host, program, version, port, protocol);
    }

    /**
     * Call remote procedure GET_ACC_TYPE_1.
     * @param arg1 parameter (of type acc_id_num) to the remote procedure call.
     * @return Result from remote procedure call (of type byte).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public byte GET_ACC_TYPE_1(acc_id_num arg1)
           throws OncRpcException, IOException {
long startTime = System.currentTimeMillis();
        XdrByte result$ = new XdrByte();
        client.call(getAccType.GET_ACC_TYPE_1, getAccType.ACC_VERS_1, arg1, result$);
long endTime = System.currentTimeMillis();
long timeTaken = endTime - startTime;
String logfileName = "log-client.txt";
FileWriter logger = new FileWriter(logfileName, true);
logger.write("Time taken by RPC for " + "GET_ACC_TYPE_1" + ": " + timeTaken + " milliseconds");
logger.close();
        return result$.byteValue();
    }

    /**
     * Call remote procedure GET_BALANCE_1.
     * @param arg1 parameter (of type acc_id_num) to the remote procedure call.
     * @return Result from remote procedure call (of type acc_balance).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public acc_balance GET_BALANCE_1(acc_id_num arg1)
           throws OncRpcException, IOException {
long startTime = System.currentTimeMillis();
        acc_balance result$ = new acc_balance();
        client.call(getAccType.GET_BALANCE_1, getAccType.ACC_VERS_1, arg1, result$);
long endTime = System.currentTimeMillis();
long timeTaken = endTime - startTime;
String logfileName = "log-client.txt";
FileWriter logger = new FileWriter(logfileName, true);
logger.write("Time taken by RPC for " + "GET_BALANCE_1" + ": " + timeTaken + " milliseconds");
logger.close();
        return result$;
    }

    /**
     * Call remote procedure SET_BALANCE_1.
     * @param arg1 parameter (of type acc_id_num) to the remote procedure call.
     * @param arg2 parameter (of type acc_balance) to the remote procedure call.
     * @return Result from remote procedure call (of type acc_balance).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public acc_balance SET_BALANCE_1(acc_id_num arg1, acc_balance arg2)
           throws OncRpcException, IOException {
long startTime = System.currentTimeMillis();
        class XdrAble$ implements XdrAble {
            public acc_id_num arg1;
            public acc_balance arg2;
            public void xdrEncode(XdrEncodingStream xdr)
                throws OncRpcException, IOException {
                arg1.xdrEncode(xdr);
                arg2.xdrEncode(xdr);
            }
            public void xdrDecode(XdrDecodingStream xdr)
                throws OncRpcException, IOException {
            }
        };
        XdrAble$ args$ = new XdrAble$();
        args$.arg1 = arg1;
        args$.arg2 = arg2;
        acc_balance result$ = new acc_balance();
        client.call(getAccType.SET_BALANCE_1, getAccType.ACC_VERS_1, args$, result$);
long endTime = System.currentTimeMillis();
long timeTaken = endTime - startTime;
String logfileName = "log-client.txt";
FileWriter logger = new FileWriter(logfileName, true);
logger.write("Time taken by RPC for " + "SET_BALANCE_1" + ": " + timeTaken + " milliseconds");
logger.close();
        return result$;
    }

    /**
     * Call remote procedure TRANSACTION_1.
     * @param arg1 parameter (of type acc_id_num) to the remote procedure call.
     * @param arg2 parameter (of type acc_id_num) to the remote procedure call.
     * @param arg3 parameter (of type acc_balance) to the remote procedure call.
     * @return Result from remote procedure call (of type transaction_pair).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public transaction_pair TRANSACTION_1(acc_id_num arg1, acc_id_num arg2, acc_balance arg3)
           throws OncRpcException, IOException {
long startTime = System.currentTimeMillis();
        class XdrAble$ implements XdrAble {
            public acc_id_num arg1;
            public acc_id_num arg2;
            public acc_balance arg3;
            public void xdrEncode(XdrEncodingStream xdr)
                throws OncRpcException, IOException {
                arg1.xdrEncode(xdr);
                arg2.xdrEncode(xdr);
                arg3.xdrEncode(xdr);
            }
            public void xdrDecode(XdrDecodingStream xdr)
                throws OncRpcException, IOException {
            }
        };
        XdrAble$ args$ = new XdrAble$();
        args$.arg1 = arg1;
        args$.arg2 = arg2;
        args$.arg3 = arg3;
        transaction_pair result$ = new transaction_pair();
        client.call(getAccType.TRANSACTION_1, getAccType.ACC_VERS_1, args$, result$);
long endTime = System.currentTimeMillis();
long timeTaken = endTime - startTime;
String logfileName = "log-client.txt";
FileWriter logger = new FileWriter(logfileName, true);
logger.write("Time taken by RPC for " + "TRANSACTION_1" + ": " + timeTaken + " milliseconds");
logger.close();
        return result$;
    }

    /**
     * Call remote procedure GET_TRANSACTION_HISTORY_1.
     * @param arg1 parameter (of type acc_id_num) to the remote procedure call.
     * @return Result from remote procedure call (of type history).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public history GET_TRANSACTION_HISTORY_1(acc_id_num arg1)
           throws OncRpcException, IOException {
long startTime = System.currentTimeMillis();
        history result$ = new history();
        client.call(getAccType.GET_TRANSACTION_HISTORY_1, getAccType.ACC_VERS_1, arg1, result$);
long endTime = System.currentTimeMillis();
long timeTaken = endTime - startTime;
String logfileName = "log-client.txt";
FileWriter logger = new FileWriter(logfileName, true);
logger.write("Time taken by RPC for " + "GET_TRANSACTION_HISTORY_1" + ": " + timeTaken + " milliseconds");
logger.close();
        return result$;
    }

}
// End of getAccTypeClient.java
