/*
 * Automatically generated by jrpcgen 1.0.7 on 16/1/15 3:48 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "getAccType" ONC/RPC program.
 */
public interface getAccType {
    public static final int ACC_VERS_1 = 1;
    public static final int MAX_HISTORY_SIZE = 50;
    public static final int NO_ACC = 0;
    public static final int GET_ACC_TYPE_1 = 1;
    public static final int ID_NUM_SIZE = 5;
    public static final int SET_BALANCE_1 = 3;
    public static final int GET_TRANSACTION_HISTORY_1 = 5;
    public static final int TRANSACTION_1 = 4;
    public static final int BANK_ACCOUNT_PROG = 9999;
    public static final int GET_BALANCE_1 = 2;
}
// End of getAccType.java
