/*
 * Automatically generated by jrpcgen 1.0.7 on 16/1/15 8:19 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.io.OutputStreamWriter;
import java.io.FileWriter;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class getAccTypeServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public getAccTypeServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public getAccTypeServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public getAccTypeServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(getAccType.BANK_ACCOUNT_PROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
try {String logfileName = "log-server.txt";FileWriter logger = new FileWriter(logfileName, true);DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");Date date = new Date();String formattedDate = dateFormat.format(date);logger.write("Remote procedure call: " + "GET_ACC_TYPE_1" + " " + formattedDate + "\n");logger.close();}catch (IOException e) {System.err.println("error opening log file");}
                acc_id_num args$ = new acc_id_num();
                call.retrieveCall(args$);
                XdrByte result$ = new XdrByte(GET_ACC_TYPE_1(args$));
                call.reply(result$);
                break;
            }
            case 2: {
try {String logfileName = "log-server.txt";FileWriter logger = new FileWriter(logfileName, true);DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");Date date = new Date();String formattedDate = dateFormat.format(date);logger.write("Remote procedure call: " + "GET_BALANCE_1" + " " + formattedDate + "\n");logger.close();}catch (IOException e) {System.err.println("error opening log file");}
                acc_id_num args$ = new acc_id_num();
                call.retrieveCall(args$);
                acc_balance result$ = GET_BALANCE_1(args$);
                call.reply(result$);
                break;
            }
            case 3: {
try {String logfileName = "log-server.txt";FileWriter logger = new FileWriter(logfileName, true);DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");Date date = new Date();String formattedDate = dateFormat.format(date);logger.write("Remote procedure call: " + "SET_BALANCE_1" + " " + formattedDate + "\n");logger.close();}catch (IOException e) {System.err.println("error opening log file");}
                class XdrAble$ implements XdrAble {
                    public acc_id_num arg1;
                    public acc_balance arg2;
                    public void xdrEncode(XdrEncodingStream xdr)
                        throws OncRpcException, IOException {
                    }
                    public void xdrDecode(XdrDecodingStream xdr)
                        throws OncRpcException, IOException {
                        arg1 = new acc_id_num(xdr);
                        arg2 = new acc_balance(xdr);
                    }
                };
                XdrAble$ args$ = new XdrAble$();
                call.retrieveCall(args$);
                acc_balance result$ = SET_BALANCE_1(args$.arg1, args$.arg2);
                call.reply(result$);
                break;
            }
            case 4: {
try {String logfileName = "log-server.txt";FileWriter logger = new FileWriter(logfileName, true);DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");Date date = new Date();String formattedDate = dateFormat.format(date);logger.write("Remote procedure call: " + "TRANSACTION_1" + " " + formattedDate + "\n");logger.close();}catch (IOException e) {System.err.println("error opening log file");}
                class XdrAble$ implements XdrAble {
                    public acc_id_num arg1;
                    public acc_id_num arg2;
                    public acc_balance arg3;
                    public void xdrEncode(XdrEncodingStream xdr)
                        throws OncRpcException, IOException {
                    }
                    public void xdrDecode(XdrDecodingStream xdr)
                        throws OncRpcException, IOException {
                        arg1 = new acc_id_num(xdr);
                        arg2 = new acc_id_num(xdr);
                        arg3 = new acc_balance(xdr);
                    }
                };
                XdrAble$ args$ = new XdrAble$();
                call.retrieveCall(args$);
                transaction_pair result$ = TRANSACTION_1(args$.arg1, args$.arg2, args$.arg3);
                call.reply(result$);
                break;
            }
            case 5: {
try {String logfileName = "log-server.txt";FileWriter logger = new FileWriter(logfileName, true);DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");Date date = new Date();String formattedDate = dateFormat.format(date);logger.write("Remote procedure call: " + "GET_TRANSACTION_HISTORY_1" + " " + formattedDate + "\n");logger.close();}catch (IOException e) {System.err.println("error opening log file");}
                acc_id_num args$ = new acc_id_num();
                call.retrieveCall(args$);
                history result$ = GET_TRANSACTION_HISTORY_1(args$);
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract byte GET_ACC_TYPE_1(acc_id_num arg1);

    public abstract acc_balance GET_BALANCE_1(acc_id_num arg1);

    public abstract acc_balance SET_BALANCE_1(acc_id_num arg1, acc_balance arg2);

    public abstract transaction_pair TRANSACTION_1(acc_id_num arg1, acc_id_num arg2, acc_balance arg3);

    public abstract history GET_TRANSACTION_HISTORY_1(acc_id_num arg1);

}
// End of getAccTypeServerStub.java
