/*
 * Automatically generated by jrpcgen 1.0.7 on 16/1/15 8:19 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.io.OutputStreamWriter;
import java.io.FileWriter;

public class history implements XdrAble {

    public int [] value;

    public history() {
    }

    public history(int [] value) {
        this.value = value;
    }

    public history(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeIntVector(value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeIntVector();
    }

}
// End of history.java
