/*
 * Automatically generated by jrpcgen 1.0.7 on 16/1/15 3:48 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class transaction_pair implements XdrAble {
    public int src_old;
    public int dst_old;
    public int src_new;
    public int dst_new;

    public transaction_pair() {
    }

    public transaction_pair(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(src_old);
        xdr.xdrEncodeInt(dst_old);
        xdr.xdrEncodeInt(src_new);
        xdr.xdrEncodeInt(dst_new);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        src_old = xdr.xdrDecodeInt();
        dst_old = xdr.xdrDecodeInt();
        src_new = xdr.xdrDecodeInt();
        dst_new = xdr.xdrDecodeInt();
    }

}
// End of transaction_pair.java
